config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root 'posts#index'

	resources :posts do 
		resource :comments
	end

	get '/about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post, only: [:create, :destroy]

	def create
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

	private

		def find_post
			@post = Post.find(params[:post_id])
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index	
		@posts = Post.order(created_at: :desc)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render :new
		end
	end

	def edit
	end

	def show
	end

	def update
		if @post.update(post_params)
			redirect_to @post 
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

		def find_post
			@post = Post.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :body)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.haml
%div.clearfix.comment
	%div.comment-content
		%p.comment-name
			%strong= comment.name
		%p.comment-body= comment.body
		%p.comment-time= "#{time_ago_in_words(comment.created_at)} ago"

		- if user_signed_in?
			%p= link_to "Delete", post_comments_path(comment.post, comment.post_id), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?'}, class: 'button'
	

app/views/comments/_form.haml
= form_for([@post, @post.comments.build]) do |f|
	-# comment_errors = @post.comments.errors.messages
	%p
		.label
			= f.label :name
			-# .errors= comment_errors[:title][0]
			= f.text_field :name

	%p
		.label
			= f.label :body
			-# .errors= comment_errors[:body][0]
			= f.text_area :body

	%p
		= f.submit "Save"

app/views/layouts/application.haml
!!!
%html
  %head
    %title BlogSrvice
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Raleway&display=swap" 
    = favicon_link_tag 'favicon.ico'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %div#sidebar
      %ul
        %li.category= link_to "BlogSrvice", root_path
        - unless current_page?(root_path)
          %li= link_to "All Posts", root_path
        %li= link_to "About", about_path

    %div#main-content
      %div#header
        - if current_page?(about_path)
          %p About this Site
        - else
          = link_to "Post Feed", root_path

        - if user_signed_in?
          %div.buttons
            - unless params[:action] == 'new'
              %button.button= link_to "Create Post", new_post_path
            %button.button= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %div.buttons
            %button.button= link_to "Login", new_user_session_path
            %button.button= link_to "Sign Up", new_user_registration_path

      - if notice.present?
        %p.notice=notice
      - if alert.present?
        %p.alert=alert

      = yield

app/views/pages/about.haml
#page-wrapper
	#profile-image
		= image_tag "profile.jpeg"

	#content
		%h1 Hey, it's me BlogSrvice
		%p Selvage vice cray, activated charcoal schlitz sriracha hoodie godard umami locavore deep v. Marfa pug slow-carb, seitan copper mug wayfarers tofu art party snackwave pok pok. Selvage williamsburg tumeric, venmo edison bulb kombucha small batch roof party gochujang butcher hella raw denim fingerstache mustache fixie. Authentic cardigan bicycle rights poutine wayfarers four loko cronut edison bulb blue bottle pickled. Gochujang woke blue bottle vaporware, cred knausgaard scenester forage lo-fi.

app/views/posts/_form.haml
= form_for @post do |f|
	%p
		.label
			= f.label :title
			.errors= @post.errors.messages[:title][0]
		= f.text_field :title
	%p
		.label
			= f.label :body
			.errors= @post.errors.messages[:body][0]
		= f.text_area :body
	%p
		= f.submit 'Save'
		- unless params[:action] == 'new'
			= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'submit'
		

app/views/posts/edit.haml
%div#page-wrapper
	%h1 Edit Post

	= render partial: 'form'

app/views/posts/index.haml
%div.post-wrapper
	- @posts.each do |post|
		%div.post
			%h3.title=link_to post.title, post_path(post), class: 'link'
			.date
				= "Created #{time_ago_in_words(post.created_at)} ago"
				- if user_signed_in?
					|
					= link_to "Edit", edit_post_path(post), class: 'link'
					|
					= link_to "Delete", post_path(post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?'}, class: 'link'
			%p.body=truncate(post.body, length: 100)
			%hr
			

app/views/posts/new.haml
%div#page-wrapper
	%h1 Create Post

	= render partial: 'form'

app/views/posts/show.haml
%div#post-content
	%h1
		=@post.title
	%p.date
		Submitted:
		= time_ago_in_words(@post.created_at)
		- if user_signed_in?
			|
			= link_to 'Edit', edit_post_path(@post), class: 'link'
	%p=@post.body

	%div#comments
		%h2="#{@post.comments.count} Comments"
		= render @post.comments
		%h3 Join Discussion
		= render partial: "comments/form"